---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    linkerd.io/extension: gamma
    component: gamma-adaptor
  name: gamma-adaptor
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      linkerd.io/extension: gamma
      component: gamma-adaptor
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        linkerd.io/extension: gamma
        component: gamma-adaptor
    spec:
      containers:
      - args:
        - gamma-adaptor
        - -cluster-domain={{.Values.clusterDomain}}
        image: {{.Values.adaptor.image.registry}}/{{.Values.adaptor.image.name}}:{{.Values.adaptor.image.tag}}
        imagePullPolicy: {{.Values.adaptor.image.pullPolicy}}
        name: gamma-adaptor
        ports:
        - containerPort: 9995
          name: admin-http
      serviceAccountName: gamma-adaptor
