---
###
### Gamma Adaptor Service
###
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gamma-adaptor
  labels:
    linkerd.io/extension: gamma
    component: gamma-adaptor
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["linkerd.io"]
  resources: ["serviceprofiles"]
  verbs: ["list", "get", "create", "update"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["list", "get", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gamma-adaptor
  labels:
    linkerd.io/extension: gamma
    component: gamma-adaptor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gamma-adaptor
subjects:
- kind: ServiceAccount
  name: gamma-adaptor
  namespace: {{.Release.Namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gamma-adaptor
  {{ include "partials.namespace" . }}
  labels:
    linkerd.io/extension: gamma
    component: gamma-adaptor
